image: node:12
stages:
  - deploy
deploy:
  stage: deploy
  script:
    - npm run build:pwa
    - scripts/rsync.sh root@janeraka.org:/mnt/volume_nyc3_01/ryru-stage ./dist/pwa/*
before_script:
  - npm install
  - apt update -y && apt install rsync -y
cache:
  paths:
    - node_modules/

